import React, { useEffect, useMemo, useState } from 'react';
import { useUIStore } from '../store/useUIStore';
import { Play, SkipBack, SkipForward, Volume2, Expand, Loader2, AlertCircle } from 'lucide-react';
import { Player } from '@remotion/player';
import { MainComposition as FallbackComposition } from '@ai-editor/remotion-core';
import { transform } from 'sucrase';
import * as remotionModules from 'remotion'; // Export everything from remotion to inject

export const VideoPreview: React.FC = () => {
  const { currentCode, compilationStatus } = useUIStore();

  // Local state to hold the dynamically evaluated component
  const [ActiveComponent, setActiveComponent] = useState<React.FC | null>(null);

  const fps = 30;
  const durationInFrames = 300; // 10 seconds at 30fps

  const playerStyle = useMemo(() => ({
     width: '100%',
     height: '100%',
     backgroundColor: 'transparent',
  }), []);

  // --- IN-MEMORY TRANSPILATION LOGIC ---
  useEffect(() => {
    useUIStore.getState().setCompilationStatus('compiling');
    useUIStore.getState().setCompilationError(null);

    // Give UI a moment to show the compiling state
    const timer = setTimeout(() => {
        try {
            // 1. Transpile JSX/TypeScript to CommonJS
            const compiledCode = transform(currentCode, {
                transforms: ['typescript', 'jsx', 'imports'],
            }).code;

            // 2. Prepare the sandbox environment (injecting React and remotion)
            const exports: any = {};
            const requireFunc = (moduleName: string) => {
                if (moduleName === 'react') return React;
                if (moduleName === 'remotion') return remotionModules;
                throw new Error(`Module '${moduleName}' not found.`);
            };

            // 3. Execute the transpiled code
            // The code generated by sucrase with 'imports' transform looks like:
            // "use strict"; Object.defineProperty(exports, "__esModule", {value: true}); const react_1 = require("react"); ... exports.MainComposition = ...
            const evaluateCode = new Function('exports', 'require', 'React', compiledCode);
            evaluateCode(exports, requireFunc, React);

            // 4. Extract the dynamically generated component
            if (exports.MainComposition && typeof exports.MainComposition === 'function') {
                setActiveComponent(() => exports.MainComposition);
                useUIStore.getState().setCompilationStatus('success');
            } else {
                throw new Error("Exported 'MainComposition' is invalid or missing.");
            }
        } catch (err: any) {
            console.error("Transpilation/Evaluation Error:", err);
            setActiveComponent(null);
            useUIStore.getState().setCompilationStatus('error');
            useUIStore.getState().setCompilationError(err.message || 'Compilation failed');
        }
    }, 300); // 300ms artificial delay to simulate async compilation

    return () => clearTimeout(timer);
  }, [currentCode]);

  // Determine which component to render in the Player
  const ComponentToRender = (compilationStatus === 'success' && ActiveComponent)
        ? ActiveComponent
        : FallbackComposition;

  return (
    <div className="flex-1 flex flex-col bg-zinc-950 p-6 relative z-0">

      {/* Container for the Remotion Player */}
      <div className="flex-1 flex flex-col min-h-0 bg-zinc-900 border border-zinc-800 rounded-lg overflow-hidden relative shadow-inner">

        {/* Top bar with Sandbox Status */}
        <div className="absolute top-0 left-0 right-0 h-12 bg-gradient-to-b from-black/60 to-transparent flex items-center justify-between px-4 z-20 pointer-events-none">
          <span className="text-zinc-200 text-sm font-medium drop-shadow-md flex items-center gap-2">
             Remotion Player
             {compilationStatus === 'compiling' && <span className="text-yellow-400 text-xs flex items-center gap-1"><Loader2 className="w-3 h-3 animate-spin"/> Compiling AI Code...</span>}
             {compilationStatus === 'success' && <span className="text-green-400 text-xs flex items-center gap-1">● AI Code Active</span>}
             {compilationStatus === 'error' && <span className="text-red-400 text-xs flex items-center gap-1"><AlertCircle className="w-3 h-3"/> Fallback Mode</span>}
          </span>
        </div>

        {/* Video Area (Remotion Player) */}
        <div className="flex-1 flex items-center justify-center relative overflow-hidden bg-black/50 z-10">
            {/* The key prop forces Player to remount completely when the component changes to prevent hook mismatches */}
            <Player
               key={compilationStatus === 'success' ? 'dynamic' : 'fallback'}
               component={ComponentToRender}
               durationInFrames={durationInFrames}
               fps={fps}
               compositionWidth={1920}
               compositionHeight={1080}
               style={playerStyle}
               controls={true}
               autoPlay={true}
               loop={true}
            />
        </div>

        {/* Playback Controls Area */}
        <div className="h-14 bg-zinc-950/80 backdrop-blur-md border-t border-zinc-800 flex items-center px-4 justify-between shrink-0 z-20 relative">

          <div className="flex items-center gap-3">
            <button className="p-2 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-full transition">
              <SkipBack className="w-4 h-4" fill="currentColor" />
            </button>
            <button className="p-2 text-white hover:bg-zinc-800 rounded-full transition bg-indigo-600 hover:bg-indigo-500">
              <Play className="w-5 h-5 ml-0.5" fill="currentColor" />
            </button>
            <button className="p-2 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-full transition">
              <SkipForward className="w-4 h-4" fill="currentColor" />
            </button>
            <span className="text-zinc-400 text-xs font-mono ml-2 border border-zinc-800 px-2 py-1 rounded bg-zinc-900">
              00:00:00 / 00:10:00
            </span>
          </div>

          <div className="flex items-center gap-3 text-zinc-400">
             <button className="p-2 hover:text-white transition">
               <Volume2 className="w-4 h-4" />
             </button>
             <button className="p-2 hover:text-white transition">
               <Expand className="w-4 h-4" />
             </button>
          </div>
        </div>
      </div>
    </div>
  );
};
